### PR TITLE
Alternative design for Emperor Beetle

### PR DESCRIPTION
**Pull request by UnorderedSigh**
**Feature**: Alternative Emperor Beetle design and associated changes to mission text.

## Feature Details

Emperor Beetle has more balanced stats, and slightly modified lore. The outfits make it a missile boat, to draw enemies away from the less durable escorts. This design is extremely powerful until it runs out of Thunderheads; then it becomes little more than a durable Shield Beetle. I have many alternative designs, but I expect the Devil Hide battle won't last long enough for that.

### Forward & Steering Engines Firing Repeater Turrets

emperor-beetle-forward

### Reverse Engines while Firing Missiles

emperor-beetle-reverse

## Usage Examples
Devil Hide battle.

## Testing Done
Sat in Devil Hide (not during battle) to see how long the Emperor Beetle would survive on its own. If I change the arrival rate to 2000 (a much more reasonable number) then the Beetle is unmatched until it runs out of missiles. Without missiles, it lasts a while, until it multiple capital ships are shooting at it.

## Performance Impact
N/A

### CODE REVIEW

**Comment by UnorderedSigh** [comment]
The commits are mistakenly from `No Body <nobody@localhost.localdomain>` but they should be squashed into one commit from @UnorderedSigh when you merge. (I forgot to git config --local the name and email.)

**Comment by Hurleveur** [comment]
I think the turrets back and front look kinda weird (but Ejo's new design ought to fix that)

Also not sure why you removed the fixed swizle, and this looks like a savefile ship (we dont need to include as many details in the ship.txt definition but I can work that out)
I'll test this out a bit soon

**Comment by Hurleveur** [comment]
I like the big explosion
However I think you gave it way too much power, as for the last design

edit: also I think that for balance we shouldnt turn the heat diss too high, and the ship may be too heavy now

I sorta merged this by making a new commit (giving credits to you ofc) and tweaking the stats and outfits.

**Comment by Hurleveur** [comment]
Closing this since conflicts and I already mitigated in but ppl didnt agree with so much korath stuff.
It'd be easier to manually copy paste the outfit set than resolving the conflicts anyway

**Pull request closed without merging**
